"""projects.init -- turn an arbitrary repository into a Quaestor project, conservatively.

WHAT "CONSERVATIVE" MEANS HERE
------------------------------
The generated manifest starts the project with exactly what it needs to be WORKED ON and nothing
it would need to be dangerous: READ_ONLY default authority is NOT granted beyond what the
operator asks for, executors start inert unless explicitly raised, and protected roots are left
EMPTY so the operator must either declare them or consciously accept a fixture-grade deployment.
An init that silently grants STANDARD_EDIT to a stranger's repository would be the one command in
this platform that widens authority by default.

Detects only PROJECT FACTS (languages, test layout) -- never orchestration internals. The output
is a starting point a human reviews, not a licence.
"""
from __future__ import annotations

import json
import os
import sys

from quaestor import branding
from quaestor.projects import config as proj_cfg

INIT_INSTRUMENT = "projects.init/1"

_MANIFEST = """\
# Generated by `quaestor init` -- review every line; defaults are deliberately restrictive.
project:
  name: {name}
  repository: .

executor:{executor_block}

commands:
  test:{test_block}

authority:
  default:
    - READ_ONLY            # raise deliberately, per project, never by omission

review:
  adversarial:
    enabled: true
    required_for: []       # platform floor always applies on top of anything listed here

evidence:
  require:
    - git_head
    - git_status
    - test_results

security:
  protected_roots: []      # DECLARE the roots this deployment must never expose
"""


#: How long one collection probe may take. A repo whose test imports hang must not hang `init`.
COLLECT_TIMEOUT_S = 60

#: Counts tests WITHOUT running them. Imports the modules -- the same cost `pytest --collect-only`
#: pays -- but executes no test body, so probing a project cannot have test side effects.
#
# IT ALSO CHECKS loader.errors. A module that fails to import does not vanish from discovery --
# unittest substitutes a synthetic _FailedTest, which countTestCases() counts as 1. So counting
# alone cannot tell "one real test" from "one module that would not import", and reporting the
# latter as a working command is exactly the mistake this whole function exists to stop.
_COUNT_DRIVER = (
    "import unittest,sys;"
    "l=unittest.TestLoader();"
    "s=l.discover(start_dir=sys.argv[1],top_level_dir=sys.argv[2],pattern=sys.argv[3]);"
    "sys.exit(3) if l.errors else print(s.countTestCases())")


def collects_tests(root: str, start: str, top: str, pattern: str = "test_*.py") -> int:
    """How many tests one unittest discovery form collects. Impure. -1 when it cannot run.

    IN A SUBPROCESS, deliberately: discovery IMPORTS the project's test modules, and importing a
    stranger's code into the process that is writing their manifest is a side effect nobody asked
    for. It also means a project whose imports explode cannot take `init` down with them.
    """
    import subprocess
    try:
        proc = subprocess.run([sys.executable, "-c", _COUNT_DRIVER, start, top, pattern],
                              cwd=root, capture_output=True, timeout=COLLECT_TIMEOUT_S,
                              shell=False)
    except Exception:  # noqa: BLE001 - a probe that cannot run is "unknown", never "fine"
        return -1
    if proc.returncode != 0:
        return -1
    try:
        return int(proc.stdout.decode("utf-8", "replace").strip().splitlines()[-1])
    except (ValueError, IndexError):
        return -1


def _unittest_candidates(root: str) -> list:
    """Discovery forms worth PROBING for this layout, best-first. PURE.

    ``-s tests -t tests`` is first when a tests/ directory exists, and that ordering is the whole
    lesson: the obvious ``-s .`` collects nothing the moment tests live in a directory that is not
    an importable package, which is the most common Python layout there is.
    """
    forms = []
    if os.path.isdir(os.path.join(root, "tests")):
        forms.append(("tests", "tests",
                      "python -m unittest discover -s tests -t tests -p test_*.py"))
    forms.append((".", ".", "python -m unittest discover -s . -p test_*.py"))
    return forms


def _detect_test_commands(root: str) -> list:
    """Which test command this repo ACTUALLY runs. Impure -- and measured, not guessed.

    Every unittest candidate is PROBED for how many tests it collects, and a form that collects
    none is not offered. The previous version inferred a command from the presence of a
    pytest.ini or a tests/ directory and wrote it into the manifest unverified; on an ordinary
    layout that command collected zero tests, so verification was permanently VACUOUS and no
    program could ever pass. A test command nobody checked is a claim, and this file is supposed
    to emit facts.
    """
    commands = []
    has = lambda n: os.path.isfile(os.path.join(root, n))  # noqa: E731
    looks_python = (has("pytest.ini") or has("pyproject.toml")
                    or os.path.isdir(os.path.join(root, "tests"))
                    or any(f.startswith("test_") for f in os.listdir(root)))
    if looks_python:
        for start, top, command in _unittest_candidates(root):
            if collects_tests(root, start, top) > 0:
                commands.append(command)
                break          # the first form that genuinely collects is the answer
        # pytest is offered as an ALTERNATIVE, never probed: it may not be installed here yet
        # be the runner in CI, and refusing to mention it because this machine lacks it would
        # be measuring the wrong box.
        commands.append("python -m pytest -q")
    if has("package.json"):
        try:
            with open(os.path.join(root, "package.json"), encoding="utf-8") as fh:
                scripts = (json.load(fh).get("scripts") or {})
            if "test" in scripts:
                # npm test first so the PROJECT's own definition wins where one exists.
                commands.insert(0, "npm test")
        except (OSError, ValueError):
            pass
    if has("Cargo.toml"):
        commands.append("cargo test")
    if has("go.mod"):
        commands.append("go test ./...")
    return commands


def _measured_collection(root: str) -> int:
    """Tests collected by the best working discovery form, or 0. Impure."""
    for start, top, _cmd in _unittest_candidates(root):
        n = collects_tests(root, start, top)
        if n > 0:
            return n
    return 0


def _detect_name(root: str) -> str:
    base = os.path.basename(os.path.abspath(root)) or "project"
    return "".join(c if (c.isalnum() or c in "-_") else "-" for c in base).strip("-").lower()


def init_repository(path: str = ".", *, force: bool = False) -> dict:
    """Write a starter manifest at ``path``. Impure. NEVER overwrites without --force."""
    root = os.path.abspath(path)
    if not os.path.isdir(root):
        return {"ok": False, "reason": "NOT_A_DIRECTORY", "detail": root}
    existing = proj_cfg.find_config(root)
    if existing and not force:
        return {"ok": False, "reason": "ALREADY_CONFIGURED", "config": existing,
                "detail": "refusing to overwrite; pass --force to replace"}
    detected = _detect_test_commands(root)
    collected = _measured_collection(root)
    if collected > 0:
        test_block = "\n" + "\n".join("    - %s" % c for c in detected[:2])
    else:
        # LOUD, NOT SILENT. A manifest that names a command collecting nothing looks configured
        # and cannot succeed: verification returns VACUOUS, the fix cycle exhausts, and the
        # program escalates having done real work. Better to hand the operator an obvious blank
        # and tell them exactly what was tried.
        test_block = ("\n    # NO TEST COMMAND VERIFIED. Discovery collected 0 tests here, so"
                      "\n    # nothing is written: an unverified command would make every"
                      "\n    # program fail verification as VACUOUS while looking configured."
                      "\n    # Add the command that runs YOUR tests, e.g.:"
                      "\n    #   - python -m pytest -q"
                      "\n    #   - python -m unittest discover -s tests -t tests -p test_*.py")
    # WHICH AGENT WILL ACTUALLY RUN. `connect` already measures this and `init` ignored it,
    # hard-coding the test double and calling it "inert until you raise it". It is not inert:
    # it runs, and it reports PASS having written nothing. A cold-start user followed the
    # documented path exactly and was told their program passed while their repository sat
    # untouched. We pin a binary we FOUND, or we write no runnable default and say why.
    from quaestor.projects import connect as connect_mod
    runnable = connect_mod.runnable_executors(root)
    if runnable:
        pick = runnable[0]
        executor_block = ("\n  default: %s      # DETECTED on this machine: %s"
                          % (pick["kind"], pick["evidence"]))
        if len(runnable) > 1:
            executor_block += ("\n  # also detected: %s"
                               % ", ".join("%s (%s)" % (r["kind"], r["evidence"])
                                           for r in runnable[1:]))
    else:
        executor_block = (
            "\n  # NO AGENT DETECTED on this machine, so NO executor is set here."
            "\n  # Leaving this blank is deliberate. The previous default was 'fake', a test"
            "\n  # double that runs, writes nothing, and reports PASS -- worse than an error,"
            "\n  # because it looks like success."
            "\n  # Install an agent and re-run `%s`, or set one by hand:"
            "\n  #   default: claude-cli" % branding.command("init"))
    out_path = os.path.join(root, "quaestor.yaml")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(_MANIFEST.format(name=_detect_name(root), test_block=test_block,
                                  executor_block=executor_block))
    cfg, reason = proj_cfg.load(out_path)
    return {"ok": True, "manifest": out_path,
            "detected_test_commands": detected,
            # MEASURED, and reported: an operator should not have to run a program to discover
            # that their test command finds nothing.
            "tests_collected": collected,
            "test_command_verified": collected > 0,
            "parsed": bool(cfg), "parse_reason": reason,
            # The measured answer to "will anything actually run?", reported at
            # init time rather than discovered three ticks later.
            "detected_executors": runnable,
            "executor_configured": bool(runnable),
            "next_steps": [
                "review %s (especially authority + security.protected_roots)" % out_path,
                ("executor.default is set to %s (detected at %s)"
                 % (runnable[0]["kind"], runnable[0]["evidence"])) if runnable
                else ("NO AGENT DETECTED -- nothing will run until you set "
                      "executor.default; install an agent and re-run, or edit "
                      "the manifest by hand"),
                "'%s' / '%s' to check the deployment"
                % (branding.command("mode show"), branding.command("doctor"))],
            "instrument": INIT_INSTRUMENT}
